{{- range .Values.clusterGroup.subscriptions }}
{{- $subs := . }}
{{- $installPlanValue := .installPlanApproval }}

{{- if $subs.namespaces }}
{{- if not $subs.disabled }}
{{- range .namespaces }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ $subs.name }}
  namespace: {{ . }}
  {{- if $subs.annotations }}
  annotations:
    {{- range $key, $value := $subs.annotations }} {{- /* We loop through the map to get key/value pairs */}}
    {{ $key }}: {{ $value | default "" | quote }}
    {{- end }}
  {{- end }}{{- /* if $subs.annotations */}}
spec:
  name: {{ $subs.name }}
  source: {{ default "redhat-operators" $subs.source }}
  sourceNamespace: {{ default "openshift-marketplace" $subs.sourceNamespace }}
  {{- if $subs.channel }}
  channel: {{ $subs.channel }}
  {{- end }} {{/* if $subs.channel */}}
  installPlanApproval: {{ coalesce $installPlanValue $.Values.global.options.installPlanApproval }}
  {{- if $subs.config }}
  {{- if $subs.config.env }}
  config:
    env:
  {{- range $subs.config.env }}
      - name: {{ .name }}
        value: {{ .value }}
  {{- end }}{{/* range $subs.config.env */}}
  {{- end }}{{/* if $subs.config.env */}}
  {{- end }}{{/* if $subs.config */}}
  {{- if $.Values.global.options.useCSV }}
  startingCSV: {{ $subs.csv }}
  {{- else if $subs.csv }}
  startingCSV: {{ $subs.csv }}
  {{- end }} {{/* if $.Values.global.options.useCSV */}}
---
{{- end }}{{/* range .namespaces */}}
{{- end }}{{/* if not $subs.disabled */}}
{{- else if not $subs.disabled }}{{/* if $subs.namespaces */}}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ $subs.name }}
  namespace: {{ default "openshift-operators" $subs.namespace }}
  {{- if $subs.annotations }}
  annotations:
    {{- range $key, $value := $subs.annotations }} {{- /* We loop through the map to get key/value pairs */}}
    {{ $key }}: {{ $value | default "" | quote }}
    {{- end }}
  {{- end }}{{- /* if $subs.annotations */}}
spec:
  name: {{ $subs.name }}
  source: {{ default "redhat-operators" $subs.source }}
  sourceNamespace: {{ default "openshift-marketplace" $subs.sourceNamespace }}
  {{- if $subs.channel }}
  channel: {{ $subs.channel }}
  {{- end }}
  installPlanApproval: {{ coalesce  $installPlanValue $.Values.global.options.installPlanApproval }}
  {{- if $subs.config }}
  {{- if $subs.config.env }}
  config:
    env:
  {{- range $subs.config.env }}
      - name: {{ .name }}
        value: {{ .value }}
  {{- end }}{{/* range $subs.config.env */}}
  {{- end }}{{/* if $subs.config.env */}}
  {{- end }}{{/* if $subs.config */}}
  {{- if $.Values.global.options.useCSV }}
  startingCSV: {{ $subs.csv }}
  {{- else if $subs.csv }}
  startingCSV: {{ $subs.csv }}
  {{- end }}{{/* if $.Values.global.options.useCSV */}}
---
{{- end }}{{/* if $subs.namespaces */}}
{{- end }}{{/* range .Values.clusterGroup.subscriptions */}}
