---
name: Verify json schema
on: [push, pull_request]

jobs:
  jsonschema_tests:
    name: Json Schema tests
    strategy:
      matrix:
        python-version: [3.11.3]
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install check-jsonschema

      - name: Verify ClusterGroup values.schema.json
        run: |
          set -e; for i in examples/*yaml; do echo "$i"; check-jsonschema --schemafile ./values.schema.json "$i"; done
